name: Build and Release escp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'  

      # Build the Go binary
      - name: Build binary
        run: go build -o escp

      # Archive the binary as an artifact
      - name: Upload Binary to Release
        uses: actions/upload-artifact@v3
        with:
          name: escp-binary
          path: ./escp
          
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Download the artifact (the binary) from the previous build job
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: escp-binary

      # Create a release and upload the binary
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: escp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
