name: Build and Release escp

on:
  push:
    branches:
      - main
      - "feature/**"    
    tags:
      - v*              

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'  # Matches the version in your go.mod

      
      - name: Build escp binary
        run: go build -o escp  

      - name: Prepare dist directory
        run: |
          mkdir -p dist
          mv escp dist/   # Move the binary to dist directory

      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/          # Upload the dist folder for later use in release

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')  

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Prepare for Release
        id: prep
        run: |
          ls -R
          echo "tags=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT  # Extract tag name from ref

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/escp"  # Upload the escp binary
          tag: ${{ github.ref }}  # Use the tag that triggered the workflow
          name: ${{ steps.prep.outputs.tags }}  # Release name is based on the tag
          body: |
            escp version ${{ steps.prep.outputs.tags }} is now available.
          draft: false
          prerelease: false
