name: Release escp Binary

on:
  release:
    types:
      - published  # This will trigger when a release is published

jobs:
  release:
    name: Build and Release escp
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'

      # Build the binary
      - name: Build escp binary
        run: go build -o escp

      # Debug step: Print the current directory structure
      - name: List directory structure after build
        run: ls -R

      # Prepare dist directory and move binary
      - name: Prepare dist directory
        run: |
          mkdir -p dist
          mv escp dist/

      # Debug step: Print directory structure after moving binary to dist/
      - name: List directory structure after moving binary
        run: ls -R dist

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Use default GitHub token
          file: dist/escp  # The binary file to upload
          asset_name: escp  # Name of the asset in the release
          tag: ${{ github.event.release.tag_name }}  # Use the tag associated with the release
