name: Build and Release escp

on:
  push:
    branches:
      - main
      - "feature/**"
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'

      # Build the binary
      - name: Build escp binary
        run: go build -o escp

      # Debug step: Print the current directory structure
      - name: List directory structure after build
        run: ls -R

      # Prepare dist directory and move binary
      - name: Prepare dist directory
        run: |
          mkdir -p dist
          mv escp dist/

      # Debug step: Print directory structure after moving binary to dist/
      - name: List directory structure after moving binary
        run: ls -R dist

      # Upload the dist folder as an artifact
      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
  
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
  
      - name: Prepare for Release
        id: prep
        run: |
          ls -R
          echo "tags=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
  
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/escp  # Upload the binary from the dist folder
          tag_name: ${{ github.ref }}  # Tag that triggered the release
          name: ${{ steps.prep.outputs.tags }}  # Use the tag as the release name
          body: escp version ${{ steps.prep.outputs.tags }} is now available.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
